repos:
-   repo: local
    hooks:
    -   id: black
        name: black
        entry: make black
        language: system

    -   id: mypy
        name: mypy
        entry: make mypy
        language: system

    -   id: pylint
        name: pylint
        entry: make pylint
        language: system

    -   id: test
        name: test
        entry: make test-prepush
        language: system
        stages: [push]

-   repo: https://github.com/commitizen-tools/commitizen
    rev: v2.17.13
    hooks:
      - id: commitizen
        stages: [commit-msg]